---
services:
  coredns:
    container_name: dns-cache
    image: tomtonic/coredns-fanout:latest
    command: -conf /etc/coredns/Corefile
    network_mode: host
    volumes:
      - .:/etc/coredns:ro
    restart: unless-stopped
